#!/bin/bash

if [[ $# -eq 0 ]]
then
	echo "$(xrandr -q)"
	exit 0
fi

xrandr --output DP-0 --auto --left-of eDP-1-1
xrandr --output DP-1 --auto --left-of eDP-1-1
xrandr --output HDMI-0 --auto --left-of eDP-1-1
